### ISSUE TITLE
Motor Output Discrepancy in Code

### ISSUE THREAD

**Issue by gentlesartori** [night-howler/protogasm#2]
@night-howler , the code (nogasm_code/nogasm_code.ino) defines MOTPIN as pin 9 but the schematic (PCB/schematic.png) shows motor output on pin 10. Also, the layout images show the Neopixel Ring DATAIN is connected to pin 10.

**Comment by LanceLake** [comment]
This seems like something that needs to be addressed.. Is this codebase no longer being reviewed?

**Comment by LanceLake** [comment]
@gentlesartori Did you come up with a solution? If so, I will update my fork and that can be used as the base.

**Comment by night-howler** [comment]
The schematic is wrong; the code is correct. MOTPIN should be Pin 9.  I must have uploaded an old schematic with the original push.  It's fixed in commit fbefd36e2d957bc667f40ca047ca02a24aec2fde which was generated from the latest EAGLE source.
